# Generated by Django 3.2.9 on 2021-11-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('razonsocial', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=40)),
                ('ruc', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=20, null=True)),
                ('wed', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedores',
                'verbose_name_plural': 'Proveedoress',
            },
        ),
    ]
